apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: challenges-autoscaler
  namespace: challenges-demo
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-math-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15