version: '2.4'

services:
  service-discovery:
    image: application/discovery-service:naive
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
    ports:
      - 8761:8080

  service-config:
    image: application/config-server:naive
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/

  examinator:
    image: application/examinator:naive
    depends_on:
      service-discovery:
        condition: service_healthy
      service-config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
      CONFIG_URL: http://service-config:8080/
    ports:
      - 8093:8080

  provider-math:
    image: application/provider-math:naive
    depends_on:
      service-discovery:
        condition: service_healthy
      service-config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
      CONFIG_URL: http://service-config:8080/

  provider-history:
    image: application/provider-history:naive
    depends_on:
      service-discovery:
        condition: service_healthy
      service-config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
      CONFIG_URL: http://service-config:8080/
    ports:
      - 8083:8080