apiVersion: v1
kind: Service
metadata:
  name: app-examinator-service
  namespace: challenges-demo
spec:
  selector:
    name: examinator
  type: LoadBalancer
  ports:
    - port: 8093
      targetPort: 8080